#!/usr/bin/env python3
"""
Render branded placeholder pages for subdomains that don't yet have a full
landing. Source of truth is `lx8_registry.yaml`.

A subdomain is only rewritten if its current ``<subdomain>/index.html`` is
the stub one-liner (``<h1>Welcome to X</h1>``) — we never clobber a real
landing page like aimem/ or tupa/.

Usage:
    python3 scripts/build_placeholders.py            # render any stubs
    python3 scripts/build_placeholders.py --check    # exit 1 if any stub
                                                     # remains unrendered
    python3 scripts/build_placeholders.py --force    # re-render any page
                                                     # we previously generated
                                                     # (detected via the
                                                     # GENERATED_MARKER sentinel
                                                     # in the file). Hand-
                                                     # written pages such as
                                                     # aimem/index.html are
                                                     # NEVER touched.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("error: pyyaml is required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY = REPO_ROOT / "lx8_registry.yaml"

# A "stub" is the historical one-line placeholder. Anything else is real
# content and we won't overwrite it unless it carries our generated marker.
STUB_RE = re.compile(r"^\s*<h1>Welcome to [^<]+</h1>\s*$", re.DOTALL)

# Sentinel string we embed in every generated page so a later --force run can
# confidently re-render only files we own. Hand-written pages never contain
# this string and are therefore safe.
GENERATED_MARKER = "<!-- generated by scripts/build_placeholders.py -->"

# Status badges per registry "status" value. Falls back to the raw string
# if a status doesn't have a curated label.
STATUS_LABELS = {
    "Active":      "● Live · Beta",
    "Alpha":       "◐ Alpha · Early access",
    "Coming Soon": "◯ Coming soon",
}

TEMPLATE = """<!DOCTYPE html>
<!-- generated by scripts/build_placeholders.py -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <meta name="description" content="{description}">
  <meta name="referrer" content="no-referrer">
  <link rel="canonical" href="https://{subdomain}.lx8labs.com/">
  <link rel="icon" href="https://avatars.githubusercontent.com/u/7157081?v=4" type="image/png">
  <meta name="theme-color" content="#6366f1">
  <meta name="color-scheme" content="dark">

  <meta property="og:type" content="website">
  <meta property="og:url" content="https://{subdomain}.lx8labs.com/">
  <meta property="og:title" content="{name} — Lx8 Labs">
  <meta property="og:description" content="{description}">

  <link rel="preconnect" href="https://fonts.bunny.net">
  <link href="https://fonts.bunny.net/css?family=Fraunces:ital,wght@1,400;0,500&family=Inter:300,400,500,600&family=Space+Grotesk:400,500,600,700&display=swap" rel="stylesheet">

  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@type": "WebSite",
    "name": "{name}",
    "url": "https://{subdomain}.lx8labs.com/",
    "description": "{description}",
    "publisher": {{ "@type": "Organization", "name": "Lx8 Labs", "url": "https://lx8labs.com" }}
  }}
  </script>

  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    :root {{
      --bg: #000000;
      --text: #f1f5f9;
      --text2: #94a3b8;
      --ind4: #818cf8;
      --border: rgba(255,255,255,0.07);
    }}
    html {{ color-scheme: dark; }}
    body {{
      font-family: 'Inter', system-ui, sans-serif;
      background: var(--bg);
      color: var(--text);
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      padding: 5rem 1.5rem;
      text-align: center;
      gap: 1.5rem;
    }}
    .brand {{ display: inline-flex; align-items: center; gap: 0.6rem; text-decoration: none; color: inherit; opacity: 0.85; transition: opacity 0.2s; }}
    .brand:hover {{ opacity: 1; }}
    .brand img {{ width: 36px; height: 36px; border-radius: 8px; border: 1px solid rgba(129,140,248,0.35); }}
    .brand-name {{ font-family: 'Space Grotesk', sans-serif; font-weight: 600; font-size: 0.95rem; }}
    .brand-name em {{ color: var(--ind4); font-style: normal; }}
    .status {{
      display: inline-flex; align-items: center; gap: 0.55rem;
      padding: 0.4rem 0.95rem;
      border: 1px solid var(--border); border-radius: 999px;
      font-family: 'Space Grotesk', sans-serif;
      font-size: 0.7rem; letter-spacing: 0.12em; text-transform: uppercase;
      color: var(--text2);
    }}
    h1 {{
      font-family: 'Fraunces', Georgia, serif;
      font-weight: 500;
      font-size: clamp(2.5rem, 6vw, 4.5rem);
      letter-spacing: -0.03em; line-height: 1.05;
      max-width: 720px;
    }}
    .desc {{ max-width: 560px; line-height: 1.7; color: var(--text2); font-size: 1.05rem; }}
    .category {{
      font-family: 'Space Grotesk', sans-serif;
      font-size: 0.7rem; letter-spacing: 0.15em; text-transform: uppercase;
      color: var(--ind4); opacity: 0.85;
    }}
    .back {{ color: var(--ind4); text-decoration: none; font-weight: 500; font-size: 0.9rem; margin-top: 0.5rem; }}
    .back:hover {{ text-decoration: underline; }}
    footer {{ font-size: 0.7rem; color: var(--text2); opacity: 0.5; margin-top: 3rem; }}
  </style>
</head>
<body>
  <a class="brand" href="https://lx8labs.com/">
    <img src="https://avatars.githubusercontent.com/u/7157081?v=4" alt="Lx8 Labs" width="36" height="36">
    <span class="brand-name">Lx8 <em>Labs</em></span>
  </a>
  <span class="status">{status_label}</span>
  <div class="category">{category}</div>
  <h1>{name}</h1>
  <p class="desc">{tagline}</p>
  <a class="back" href="https://lx8labs.com/">← Back to lx8labs.com</a>
  <footer>© 2026 Lx8 Labs · {subdomain}.lx8labs.com</footer>
</body>
</html>
"""


def title_for(product: dict) -> str:
    return f"{product['name']} — Lx8 Labs"


def render(product: dict) -> str:
    return TEMPLATE.format(
        title=title_for(product),
        name=product["name"],
        description=product["description"],
        tagline=product.get("tagline", product["description"]),
        subdomain=product["subdomain"],
        category=product["category"],
        status_label=STATUS_LABELS.get(product["status"], product["status"]),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if any stub remains unrendered.")
    parser.add_argument("--force", action="store_true",
                        help="Rewrite all subdomains, not only stubs.")
    args = parser.parse_args()

    with REGISTRY.open() as f:
        registry = yaml.safe_load(f)

    rewrote: list[str] = []
    stubs_remaining: list[str] = []

    for product in registry.get("products", []):
        # The registry uses `description` as the human label; the human-facing
        # name is the subdomain by convention, except where we override.
        product.setdefault("name", product["description"].split(" — ")[0])

        sub = product["subdomain"]
        index_path = REPO_ROOT / sub / "index.html"
        if not index_path.exists():
            print(f"  ! {sub}: no index.html — skipping (folder may not exist)")
            continue

        body = index_path.read_text()
        is_stub = bool(STUB_RE.match(body))
        is_generated = GENERATED_MARKER in body

        if args.check:
            if is_stub:
                stubs_remaining.append(sub)
            continue

        # The decision matrix:
        #   stub        -> always render
        #   generated   -> render only when --force is set (update template)
        #   real / hand-written -> NEVER touch, even with --force
        if not (is_stub or (is_generated and args.force)):
            reason = "hand-written content present" if not is_generated else "previously generated; pass --force to refresh"
            print(f"  · {sub}: {reason} — skipping")
            continue

        index_path.write_text(render(product))
        rewrote.append(sub)
        print(f"  ✓ {sub}: placeholder written")

    if args.check:
        if stubs_remaining:
            print("Stubs found:", ", ".join(stubs_remaining), file=sys.stderr)
            return 1
        print("No stubs remaining.")
        return 0

    print(f"Done. Rewrote {len(rewrote)} placeholder(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
