#!/usr/bin/env python3
"""
Walk `insights/*.html`, parse the article metadata (title, description,
publication date, author) from `<meta>` tags, and emit `feed.xml` — the
RSS 2.0 feed at https://lx8labs.com/feed.xml.

`lastBuildDate` is set to the latest `article:published_time` across all
included posts so the file is deterministic across machines (no "today"
drift). Per-item `pubDate` comes from the matching `article:published_time`
meta tag. If a post's date is missing, `git log -1 --format=%cs` of the
file is used as the fallback.

This mirrors `scripts/generate_sitemap.py` so the operational pattern is
identical: write it, commit it, add a `--check` mode that CI runs to
prevent drift.

Usage:
    python3 scripts/generate_feed.py            # rewrite feed.xml
    python3 scripts/generate_feed.py --check    # exit 1 if committed
                                                # feed.xml drifts from
                                                # generated
    python3 scripts/generate_feed.py --stdout   # print, don't write
"""
from __future__ import annotations

import argparse
import datetime
import html
import re
import subprocess
import sys
from email.utils import format_datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FEED = REPO_ROOT / "feed.xml"
INSIGHTS = REPO_ROOT / "insights"
HOST = "https://lx8labs.com"

META_TITLE_RE = re.compile(r"<title>([^<]+)</title>", re.IGNORECASE)
META_RE = re.compile(
    r'<meta\s+(?:name|property)="([^"]+)"\s+content="([^"]*)"\s*/?>',
    re.IGNORECASE,
)


def extract_meta(path: Path) -> dict[str, str]:
    """Pull <title> + every <meta name/property=… content=…> into a dict.

    Strips the " · Lx8 Labs" suffix from the title (it's not useful in an
    RSS reader) and unescapes entity references so the feed carries the
    raw text, not double-encoded markup.
    """
    text = path.read_text()
    out: dict[str, str] = {}
    title_match = META_TITLE_RE.search(text)
    if title_match:
        raw_title = html.unescape(title_match.group(1)).strip()
        # Strip trailing " · Lx8 Labs" / " — Lx8 Labs" / " | Lx8 Labs"
        raw_title = re.sub(r"\s*[·—|]\s*Lx8 Labs\s*$", "", raw_title)
        out["title"] = raw_title
    for m in META_RE.finditer(text):
        key = m.group(1).lower()
        value = html.unescape(m.group(2)).strip()
        out.setdefault(key, value)
    return out


def git_lastmod(path: Path) -> str | None:
    """YYYY-MM-DD of latest git commit touching `path`, or None on miss."""
    try:
        out = subprocess.check_output(
            ["git", "log", "-1", "--format=%cs", "--", str(path.relative_to(REPO_ROOT))],
            cwd=REPO_ROOT, stderr=subprocess.DEVNULL,
        ).decode().strip()
        return out or None
    except subprocess.CalledProcessError:
        return None


def to_rfc2822(date_str: str) -> str:
    """Convert YYYY-MM-DD to RFC 2822 (RSS-required format) at 12:00 UTC."""
    dt = datetime.datetime.strptime(date_str, "%Y-%m-%d").replace(
        hour=12, minute=0, second=0, tzinfo=datetime.timezone.utc
    )
    return format_datetime(dt)


def collect_items() -> list[dict]:
    """Return one dict per insight article, sorted newest-first."""
    items: list[dict] = []
    if not INSIGHTS.exists():
        return items
    for html_path in sorted(INSIGHTS.glob("*.html")):
        if html_path.name == "index.html":
            continue
        meta = extract_meta(html_path)
        pubdate = (
            meta.get("article:published_time")
            or git_lastmod(html_path)
            or datetime.date.today().isoformat()
        )
        items.append({
            "title": meta.get("title", html_path.stem),
            "link": f"{HOST}/insights/{html_path.name}",
            "description": meta.get("description") or meta.get("og:description") or "",
            "pubdate": pubdate,
            "author": meta.get("article:author", "Alexei Ferreira"),
            "category": meta.get("article:section", "Insights"),
        })
    items.sort(key=lambda x: x["pubdate"], reverse=True)
    return items


def xml_escape(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;"))


def render(items: list[dict]) -> str:
    last_build = max((i["pubdate"] for i in items), default=datetime.date.today().isoformat())
    last_build_rfc = to_rfc2822(last_build)

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!--",
        "  Generated by scripts/generate_feed.py — do not edit by hand.",
        "  Pulls per-article metadata from each insights/*.html and emits",
        "  RSS 2.0. lastBuildDate is the newest article:published_time so",
        "  the file is byte-stable across CI runs (no 'today' drift).",
        "-->",
        '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/">',
        "<channel>",
        "  <title>Lx8 Labs — Insights</title>",
        f"  <link>{HOST}/</link>",
        "  <description>Field notes from the lab. DevOps post-mortems, AI experiments, paper breakdowns. Once or twice a month.</description>",
        "  <language>en-us</language>",
        f"  <lastBuildDate>{last_build_rfc}</lastBuildDate>",
        f'  <atom:link href="{HOST}/feed.xml" rel="self" type="application/rss+xml" />',
        "  <image>",
        "    <url>https://avatars.githubusercontent.com/u/7157081?v=4</url>",
        "    <title>Lx8 Labs</title>",
        f"    <link>{HOST}/</link>",
        "  </image>",
        "  <copyright>© 2013–2026 Lx8 Labs · Founded by Alexei Ferreira</copyright>",
        "  <managingEditor>contact@lx8labs.com (Alexei Ferreira)</managingEditor>",
        "  <generator>scripts/generate_feed.py — lx8labs.com</generator>",
        "",
    ]

    for item in items:
        lines += [
            "  <item>",
            f"    <title>{xml_escape(item['title'])}</title>",
            f"    <link>{item['link']}</link>",
            f'    <guid isPermaLink="true">{item["link"]}</guid>',
            f"    <pubDate>{to_rfc2822(item['pubdate'])}</pubDate>",
            f"    <dc:creator>{xml_escape(item['author'])}</dc:creator>",
            f"    <category>{xml_escape(item['category'])}</category>",
            f"    <description>{xml_escape(item['description'])}</description>",
            "  </item>",
            "",
        ]

    lines.append("</channel>")
    lines.append("</rss>")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if committed feed.xml drifts from generated.")
    parser.add_argument("--stdout", action="store_true",
                        help="Print to stdout instead of writing.")
    args = parser.parse_args()

    rendered = render(collect_items())

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        current = FEED.read_text() if FEED.exists() else ""
        if current != rendered:
            print("feed.xml is out of date. Run:", file=sys.stderr)
            print("    python3 scripts/generate_feed.py", file=sys.stderr)
            return 1
        print("feed.xml is up to date.")
        return 0

    FEED.write_text(rendered)
    item_count = rendered.count("<item>")
    print(f"Wrote {FEED.relative_to(REPO_ROOT)} ({item_count} item(s)).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
