#!/usr/bin/env python3
"""
Walk the static site, emit sitemap.xml for the apex host (lx8labs.com).

We intentionally only index the apex. Each subdomain (aimem, tupa, …) is a
standalone Firebase Hosting site and is responsible for its own sitemap.

Inclusion rules:
  - Any ``<dir>/index.html`` becomes ``https://lx8labs.com/<dir>/``.
  - ``./index.html`` becomes ``https://lx8labs.com/``.
  - Loose ``*.html`` files under top-level public sections (currently only
    ``insights/``) are listed by full path.
  - Everything under the directories in ``IGNORED_TOP`` is skipped — those
    are infra/build artefacts, not user-facing pages.

The order is stable (alphabetical) so the file diffs cleanly. ``lastmod`` is
the latest git-tracked mtime of the file (falls back to today if the file
isn't tracked yet).

Usage:
    python3 scripts/generate_sitemap.py            # rewrite sitemap.xml
    python3 scripts/generate_sitemap.py --check    # exit 1 if drift
    python3 scripts/generate_sitemap.py --stdout   # print, don't write
"""
from __future__ import annotations

import argparse
import datetime
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SITEMAP = REPO_ROOT / "sitemap.xml"
HOST = "https://lx8labs.com"

# Top-level directories we never index. Subdomains are separate hosting
# sites (own sitemaps); admin/dashboard/login are private surfaces; infra
# isn't user-facing.
IGNORED_TOP = {
    "aimem", "tupa", "tupaide", "suit",
    "bipartitebook", "installations", "mattermem",
    "dashboard", "admin", "login",
    "functions", "scripts", "i18n", "infrastructure", "docs",
    ".git", ".github", ".firebase", "__pycache__", "node_modules",
}

# Per-section "loose pages" — directories where individual .html files
# matter (not just <dir>/index.html). Keep this minimal.
LOOSE_SECTIONS = {"insights"}

# Suggested SEO weights. Anything not in here defaults to 0.5 / monthly.
PRIORITIES: dict[str, tuple[str, str]] = {
    "":              ("1.0", "weekly"),
    "algorithms/":   ("0.9", "monthly"),
    "products/":     ("0.9", "monthly"),
    "tupa/":         ("0.8", "monthly"),
    "courses/":      ("0.8", "monthly"),
    "research/":     ("0.8", "monthly"),
    "about/":        ("0.7", "monthly"),
    "theory/":       ("0.7", "monthly"),
    "team/":         ("0.7", "monthly"),
    "now/":          ("0.6", "monthly"),
    "changelog/":    ("0.6", "weekly"),
    "unity/":        ("0.5", "monthly"),
    "shop/":         ("0.5", "monthly"),
    "impressum/":    ("0.3", "yearly"),
    "privacy/":      ("0.3", "yearly"),
}


def git_lastmod(path: Path) -> str:
    """Return YYYY-MM-DD of latest git commit touching `path` (UTC)."""
    try:
        out = subprocess.check_output(
            ["git", "log", "-1", "--format=%cs", "--", str(path.relative_to(REPO_ROOT))],
            cwd=REPO_ROOT, stderr=subprocess.DEVNULL,
        ).decode().strip()
        if out:
            return out
    except subprocess.CalledProcessError:
        pass
    return datetime.date.today().isoformat()


def discover() -> list[tuple[str, str]]:
    """Return list of (relative_path_from_apex, lastmod) entries, sorted."""
    entries: list[tuple[str, Path]] = []

    # Homepage
    if (REPO_ROOT / "index.html").exists():
        entries.append(("", REPO_ROOT / "index.html"))

    for top in sorted(REPO_ROOT.iterdir()):
        if not top.is_dir() or top.name in IGNORED_TOP:
            continue
        if (top / "index.html").exists():
            entries.append((f"{top.name}/", top / "index.html"))

        if top.name in LOOSE_SECTIONS:
            for html in sorted(top.glob("*.html")):
                if html.name == "index.html":
                    continue
                entries.append((f"{top.name}/{html.name}", html))

    return [(rel, git_lastmod(p)) for rel, p in entries]


def render(entries: list[tuple[str, str]]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!--",
        "  Generated by scripts/generate_sitemap.py — do not edit by hand.",
        "  Each subdomain is a standalone Firebase Hosting site and",
        "  publishes its own sitemap.",
        "-->",
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for rel, lastmod in entries:
        prio, freq = PRIORITIES.get(rel, ("0.5", "monthly"))
        lines += [
            "  <url>",
            f"    <loc>{HOST}/{rel}</loc>",
            f"    <lastmod>{lastmod}</lastmod>",
            f"    <changefreq>{freq}</changefreq>",
            f"    <priority>{prio}</priority>",
            "  </url>",
        ]
    lines.append("</urlset>")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if committed sitemap.xml drifts from generated.")
    parser.add_argument("--stdout", action="store_true",
                        help="Print to stdout instead of writing.")
    args = parser.parse_args()

    rendered = render(discover())

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        current = SITEMAP.read_text() if SITEMAP.exists() else ""
        if current != rendered:
            print("sitemap.xml is out of date. Run:", file=sys.stderr)
            print("    python3 scripts/generate_sitemap.py", file=sys.stderr)
            return 1
        print("sitemap.xml is up to date.")
        return 0

    SITEMAP.write_text(rendered)
    print(f"Wrote {SITEMAP.relative_to(REPO_ROOT)} ({rendered.count('<url>')} URLs).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
