#!/usr/bin/env python3
"""
Keep the inline <meta http-equiv="Content-Security-Policy"> tag in every
authored HTML page in lock-step with the canonical CSP defined in
firebase.json.

Why this exists:
  - The Firebase Hosting CSP is the single source of truth for the
    subdomains served by Firebase.
  - The apex domain (lx8labs.com) is served by GitHub Pages, which can't
    set HTTP response headers. Without a <meta> CSP, the homepage and root
    directory pages have NO security policy in the browser at all.

What this script does:
  - Parses the apex-target CSP value from firebase.json (the `main` hosting
    target).
  - Strips directives that meta CSP doesn't support (frame-ancestors,
    sandbox, report-uri, report-to). The framebusting script that's already
    present on every page covers frame-ancestors 'none'.
  - Updates or inserts a `<meta http-equiv="Content-Security-Policy" ...>`
    immediately after `<head>` in every authored HTML page.

Usage:
    python3 scripts/sync_csp.py            # rewrite drifted/missing tags
    python3 scripts/sync_csp.py --check    # exit 1 on any drift (CI)
    python3 scripts/sync_csp.py --diff     # show what would change

Excluded paths (build artefacts, vendored, generated):
  - node_modules anywhere
  - bipartitebook/  (Next.js export)
  - */dashboard/index.html (Vite-built React app)
  - functions/, scripts/, i18n/
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIREBASE_JSON = REPO_ROOT / "firebase.json"

# Directives that are valid in a response header but ignored in a <meta>
# tag. Strip them so we don't paste invalid policy that confuses linters.
META_INCOMPATIBLE = {"frame-ancestors", "sandbox", "report-uri", "report-to"}

EXCLUDED_PATH_PARTS = {
    "node_modules", "__pycache__", ".git",
    "bipartitebook", "functions", "scripts", "i18n",
}

# Skip the Vite-built dashboard entry points — they're regenerated by
# `npm run build` and the meta tag would be overwritten on the next deploy.
EXCLUDED_FILES = {
    "dashboard/index.html",
    "aimem/dashboard/index.html",
    "installations/dashboard/index.html",
    "mattermem/dashboard/index.html",
    "suit/dashboard/index.html",
    "tupa/dashboard/index.html",
    "tupaide/dashboard/index.html",
}


META_RE = re.compile(
    r'<meta\s+http-equiv="Content-Security-Policy"[^>]*>',
    re.IGNORECASE,
)
HEAD_OPEN_RE = re.compile(r"(<head[^>]*>)", re.IGNORECASE)


def load_canonical_csp() -> str:
    """Return the CSP string from the `main` hosting target in firebase.json."""
    with FIREBASE_JSON.open() as f:
        cfg = json.load(f)
    for site in cfg.get("hosting", []):
        if site.get("target") != "main":
            continue
        for header_block in site.get("headers", []):
            for header in header_block.get("headers", []):
                if header.get("key", "").lower() == "content-security-policy":
                    return header["value"]
    raise SystemExit("error: could not find CSP in firebase.json hosting target 'main'")


def strip_meta_incompatible(csp: str) -> str:
    """Drop directives invalid inside a <meta> tag."""
    parts = [p.strip() for p in csp.split(";") if p.strip()]
    kept = []
    for p in parts:
        name = p.split(None, 1)[0].lower()
        if name not in META_INCOMPATIBLE:
            kept.append(p)
    return "; ".join(kept) + ";"


def render_tag(csp_value: str) -> str:
    return f'<meta http-equiv="Content-Security-Policy" content="{csp_value}">'


def authored_html_files() -> list[Path]:
    out: list[Path] = []
    for path in REPO_ROOT.rglob("*.html"):
        rel = path.relative_to(REPO_ROOT)
        rel_str = str(rel).replace("\\", "/")
        if rel_str in EXCLUDED_FILES:
            continue
        if any(part in EXCLUDED_PATH_PARTS for part in rel.parts):
            continue
        out.append(path)
    return sorted(out)


def update_file(path: Path, desired_tag: str, mode: str) -> tuple[bool, str]:
    """Return (drifted_or_changed, message). `mode` ∈ {'write', 'check', 'diff'}."""
    text = path.read_text()
    rel = path.relative_to(REPO_ROOT)

    new_text = text
    existing_match = META_RE.search(text)

    if existing_match:
        if existing_match.group(0) == desired_tag:
            return False, ""
        new_text = text[:existing_match.start()] + desired_tag + text[existing_match.end():]
    else:
        head_match = HEAD_OPEN_RE.search(text)
        if not head_match:
            return False, f"  {rel}: no <head> — skipped"
        insert_at = head_match.end()
        # Place the meta tag on its own line, indented two spaces.
        new_text = text[:insert_at] + f"\n  {desired_tag}" + text[insert_at:]

    if mode == "check":
        return True, f"  drift: {rel}"
    if mode == "diff":
        return True, f"  would update: {rel}"
    path.write_text(new_text)
    return True, f"  ✓ {rel}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if any file's meta CSP doesn't match the canonical value.")
    parser.add_argument("--diff", action="store_true",
                        help="Print which files would change without writing.")
    args = parser.parse_args()

    if args.check and args.diff:
        print("error: --check and --diff are mutually exclusive", file=sys.stderr)
        return 2

    canonical = load_canonical_csp()
    meta_value = strip_meta_incompatible(canonical)
    desired_tag = render_tag(meta_value)

    mode = "check" if args.check else ("diff" if args.diff else "write")
    print(f"Canonical CSP (stripped for meta): {meta_value[:80]}…")
    print(f"Scanning authored HTML…")

    changed = 0
    for path in authored_html_files():
        drifted, msg = update_file(path, desired_tag, mode=mode)
        if drifted:
            changed += 1
            if msg:
                print(msg)

    if args.check:
        if changed:
            print(f"\n{changed} file(s) have drifted from canonical CSP.", file=sys.stderr)
            print("Run: python3 scripts/sync_csp.py", file=sys.stderr)
            return 1
        print("All authored pages match canonical CSP.")
        return 0

    print(f"\n{changed} file(s) updated." if mode == "write"
          else f"\n{changed} file(s) would update.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
